Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2023-02, with the labels that each got.

#5 feat: Use ghcr.io rather than Docker Hub
  .goreleaser.yml
Labels: feature

#9 feat: deploy Calico with ClusterResourceSet
  .tool-versions
  cmd/capi-runtime-extensions/main.go
  config/certmanager/certificate.yaml
  config/default/extension.yaml
  config/default/extension_config.yaml
  config/default/extension_image_patch.yaml
  config/default/kustomization.yaml
  config/default/rolebinding.yaml
  go.mod
  go.sum
  hack/addons/update-calico-manifests.sh
  hack/common.sh
  make/addons.mk
  make/all.mk
  pkg/addons/cni.go
  pkg/addons/crs.go
  pkg/addons/templates/cni/calico-cni-installation-crs.yaml
  pkg/addons/templates/cni/docker-calico-cni-installation-configmap.yaml
  pkg/addons/templates/cni/tigera-operator-configmap.yaml
  pkg/handlers/lifecycle/handlers.go
  pkg/k8s/client/client.go
Labels: feature

#10 feat: Add helm chart
  .github/workflows/checks.yml
  .github/workflows/goreleaser.yaml
  .pre-commit-config.yaml
  .tool-versions
  charts/capi-runtime-extensions/Chart.yaml
  charts/capi-runtime-extensions/README.md
  charts/capi-runtime-extensions/README.md.gotmpl
  charts/capi-runtime-extensions/templates/_helpers.tpl
  charts/capi-runtime-extensions/templates/certificate.yaml
  charts/capi-runtime-extensions/templates/clusterrole.yaml
  charts/capi-runtime-extensions/templates/clusterrolebinding.yaml
  charts/capi-runtime-extensions/templates/deployment.yaml
  charts/capi-runtime-extensions/templates/extensionconfig.yaml
  charts/capi-runtime-extensions/templates/issuer_selfsigned.yaml
  charts/capi-runtime-extensions/templates/service.yaml
  charts/capi-runtime-extensions/templates/serviceaccount.yaml
  charts/capi-runtime-extensions/values.yaml
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/default/extension.yaml
  config/default/extension_config.yaml
  config/default/extension_image_patch.yaml
  config/default/extension_pull_policy.yaml
  config/default/extension_webhook_patch.yaml
  config/default/kustomization.yaml
  config/default/kustomizeconfig.yaml
  config/default/role.yaml
  config/default/rolebinding.yaml
  config/default/service.yaml
  config/default/service_account.yaml
  hack/addons/update-calico-manifests.sh
  make/addons.mk
  make/all.mk
  make/kubebuilder.mk
  pkg/addons/templates/cni/tigera-operator-configmap.yaml
Labels: feature

#13 fix: Fix panic when applying CNI CRS via hook
  .github/workflows/checks.yml
  charts/capi-runtime-extensions/templates/clusterrole.yaml
  make/clusterctl.mk
  pkg/addons/crs.go
  pkg/addons/templates/cni/calico-cni-installation-crs.yaml
  pkg/addons/templates/cni/docker-calico-cni-installation-configmap.yaml
  pkg/handlers/lifecycle/handlers.go
  pkg/k8s/client/client.go
Labels: fix

#14 chore: add more dev docs
  README.md
Labels: ignore-for-release

#16 fix: Calico deployment to work with CAPD template
  README.md
  hack/addons/update-calico-manifests.sh
  make/addons.mk
  pkg/addons/templates/cni/tigera-operator-configmap.yaml
Labels: fix

#22 feat: Add Flux addons provider
  .github/dependabot.yml
  .tool-versions
  README.md
  charts/capi-runtime-extensions/README.md
  charts/capi-runtime-extensions/templates/clusterrole.yaml
  charts/capi-runtime-extensions/templates/deployment.yaml
  charts/capi-runtime-extensions/values.schema.json
  charts/capi-runtime-extensions/values.yaml
  cmd/capi-runtime-extensions/flags.go
  cmd/capi-runtime-extensions/main.go
  go.mod
  go.sum
  hack/addons/update-calico-manifests.sh
  make/all.mk
  make/dev.mk
  make/flux.mk
  pkg/addons/clusterresourcesets/cni.go
  pkg/addons/clusterresourcesets/crs.go
  pkg/addons/clusterresourcesets/templates/cni/calico-cni-installation-crs.yaml
  pkg/addons/clusterresourcesets/templates/cni/docker-calico-cni-installation-configmap.yaml
  pkg/addons/clusterresourcesets/templates/cni/tigera-operator-configmap.yaml
  pkg/addons/fluxhelmrelease/cni.go
  pkg/handlers/lifecycle/handlers.go
  pkg/k8s/client/client.go
Labels: feature

#25 feat: Add API boilerplate
  .pre-commit-config.yaml
  .tool-versions
  PROJECT
  api/v1alpha1/clusteraddon_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/capi-runtime-extensions/crds/clusteraddons.labs.d2iq.io_clusteraddons.yaml
  charts/capi-runtime-extensions/templates/role.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/controller/clusteraddon_controller.go
  internal/controller/suite_test.go
  make/go.mk
Labels: feature

#26 feat: Add ClusterAddonSet and ClusterAddon API types
  api/v1alpha1/clusteraddon_types.go
  api/v1alpha1/clusteraddonset_types.go
  api/v1alpha1/common_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/capi-runtime-extensions/crds/clusteraddons.labs.d2iq.io_clusteraddons.yaml
  charts/capi-runtime-extensions/crds/clusteraddons.labs.d2iq.io_clusteraddonsets.yaml
  charts/capi-runtime-extensions/templates/role.yaml
  internal/controller/clusteraddonset_controller.go
Labels: feature

#27 feat: Enable controller manager
  .gitignore
  charts/capi-runtime-extensions/README.md
  charts/capi-runtime-extensions/templates/_helpers.tpl
  charts/capi-runtime-extensions/templates/certificate.yaml
  charts/capi-runtime-extensions/templates/certificates.yaml
  charts/capi-runtime-extensions/templates/clusterrole.yaml
  charts/capi-runtime-extensions/templates/clusterrolebinding.yaml
  charts/capi-runtime-extensions/templates/deployment.yaml
  charts/capi-runtime-extensions/templates/extensionconfig.yaml
  charts/capi-runtime-extensions/templates/issuer_selfsigned.yaml
  charts/capi-runtime-extensions/templates/role.yaml
  charts/capi-runtime-extensions/templates/service.yaml
  charts/capi-runtime-extensions/values.schema.json
  charts/capi-runtime-extensions/values.yaml
  cmd/capi-runtime-extensions/main.go
  go.mod
  go.sum
  internal/controllermanager/controllermanager.go
  internal/controllers/clusteraddonset_controller.go
  internal/controllers/clusteraddonset_controller_test.go
  internal/controllers/suite_test.go
  internal/runtimehooks/webhooks/flags.go
  internal/runtimehooks/webhooks/server.go
  pkg/addons/clusterresourcesets/doc.go
  pkg/addons/fluxhelmrelease/doc.go
Labels: feature

#29 feat: delete Services type LoadBalancer on BeforeClusterDelete
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/handlers/lifecycle/handlers.go
  pkg/k8s/annotations/annotations.go
  pkg/k8s/deleter/deleter.go
  pkg/k8s/deleter/deleter_test.go
Labels: feature
