Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-07, with the labels that each got.

#765 fix: Add strategy to Nutanix CCM addon in examples
  examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/addons/kustomize/nutanix-ccm/kustomization.yaml.tmpl
  hack/examples/patches/nutanix/ccm.yaml
  test/e2e/ccm_helpers.go
Labels: fix

#767 release(main): v0.11.2
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#776 fix: Copy ClusterClasses and Templates without their owner references
  pkg/controllers/namespacesync/copy.go
Labels: fix

#775 fix: Namespacesync controller should reconcile an updated namespace
  cmd/main.go
  pkg/controllers/namespacesync/controller.go
  pkg/controllers/namespacesync/controller_test.go
  pkg/controllers/namespacesync/suite_test.go
Labels: fix

#777 feat: Add waiter for object
  pkg/wait/wait.go
  pkg/wait/wait_test.go
Labels: feature

#774 fix: use minimal image when deploying nfd chart
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
Labels: fix

#778 feat: Define ServiceLoadBalancer Configuration API
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/addons/serviceloadbalancer.md
Labels: feature

#771 feat: Use HelmAddon as default addon strategy
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  examples/capi-quick-start/aws-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/aws-cluster-cilium-helm-addon.yaml
  examples/capi-quick-start/docker-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/docker-cluster-cilium-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/examples/overlays/clusters/aws/calico/helm-addon/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/aws/cilium/helm-addon/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/docker/calico/helm-addon/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/docker/cilium/helm-addon/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/nutanix/calico/helm-addon/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/nutanix/cilium/helm-addon/kustomization.yaml.tmpl
  hack/examples/patches/aws/helm-addon-strategy.yaml
  hack/examples/patches/docker/csi-helm-addon-strategy.yaml
  hack/examples/patches/helm-addon-strategy.yaml
Labels: feature

#783 feat: Apply MetalLB configuration to remote cluster
  pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/handler_test.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/configuration.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
Labels: feature

#785 feat: Update addon versions
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/virtual-ip/kube-vip/manifests/kube-vip-configmap.yaml
  hack/addons/kustomize/cluster-autoscaler/kustomization.yaml.tmpl
  hack/addons/kustomize/nfd/kustomization.yaml.tmpl
  hack/addons/mindthegap-helm-registry/repos.yaml
  hack/addons/update-cluster-autoscaler.sh
  hack/addons/update-kube-vip-manifests.sh
  make/addons.mk
Labels: feature

#770 release(main): v0.12.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#791 fix: Only create MetalLB configuration when necessary
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/configuration.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
Labels: fix

#795 fix: add omitempty to addon strategy
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/handlers/generic/lifecycle/ccm/aws/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/variables_test.go
  pkg/handlers/generic/lifecycle/cni/calico/handler.go
  pkg/handlers/generic/lifecycle/cni/cilium/handler.go
  pkg/handlers/generic/lifecycle/cni/variables_test.go
  pkg/handlers/generic/lifecycle/csi/awsebs/handler.go
  pkg/handlers/generic/lifecycle/csi/localpath/handler.go
  pkg/handlers/generic/lifecycle/csi/nutanix/handler.go
  pkg/handlers/generic/lifecycle/csi/snapshotcontroller/handler.go
  pkg/handlers/generic/lifecycle/csi/variables_test.go
  pkg/handlers/generic/lifecycle/nfd/handler.go
  pkg/handlers/generic/lifecycle/nfd/variables_test.go
  test/e2e/ccm_helpers.go
  test/e2e/clusterautoscaler_helpers.go
  test/e2e/cni_helpers.go
  test/e2e/csi_helpers.go
  test/e2e/nfd_helpers.go
Labels: fix

#805 fix: update CCM to 0.3.4 to fix sweet32 issue
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: fix

#807 fix: Clean up MetalLB pod security standards labels
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
  pkg/handlers/utils/utils.go
Labels: fix

#808 feat: Secure ciphers, min TLS v1.2, and disable auto TLS for etcd
  pkg/handlers/generic/mutation/etcd/inject.go
  pkg/handlers/generic/mutation/etcd/inject_test.go
Labels: feature

#784 feat: Bump default k8s version for tests to v1.29.6
  .github/workflows/e2e.yml
  README.md
  make/go.mk
  test/e2e/config/caren.yaml
  test/e2e/e2e_suite_test.go
Labels: feature

#810 fix: Fix ownership of ClusterAutoscaler resources
  pkg/handlers/generic/lifecycle/ccm/aws/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_crs.go
  pkg/handlers/generic/lifecycle/csi/awsebs/strategy_crs.go
  pkg/handlers/generic/lifecycle/csi/localpath/strategy_crs.go
  pkg/handlers/generic/lifecycle/csi/snapshotcontroller/strategy_crs.go
  pkg/handlers/generic/lifecycle/nfd/strategy_crs.go
  pkg/handlers/utils/utils.go
  test/e2e/ownerreference_helpers.go
  test/e2e/quick_start_test.go
Labels: fix

#804 release(main): v0.13.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#811 fix: generated API file
  api/v1alpha1/zz_generated.deepcopy.go
Labels: fix

#814 fix: category race condition by updating Nutanix CSI to 3.0.0-2458
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/kustomize/nutanix-storage-csi/kustomization.yaml.tmpl
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: fix

#815 fix: use production repo for Nutanix CSI to 3.0.0-2458
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/kustomize/nutanix-storage-csi/kustomization.yaml.tmpl
  hack/addons/mindthegap-helm-registry/repos.yaml
Labels: fix

#812 release(main): v0.13.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#817 fix: Remove unused setting from Nutanix CSI chart
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
Labels: fix

#820 fix: Use correct GA Nutanix CSI version
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: fix

#818 release(main): v0.13.2
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#821 fix: add cluster domain with final dot to no proxy list
  api/v1alpha1/http_proxy.go
  api/v1alpha1/http_proxy_test.go
Labels: fix

#825 release(main): v0.13.3
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#830 fix: ClusterAutoscaler addon ownership for move
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/utils/utils.go
Labels: fix
