Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-09, with the labels that each got.

#895 fix: Remove deprecated toleration for node-role.kubernetes.io/master
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.27.9-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.28.9-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.29.6-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.2-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.31.0-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/local-path-provisioner-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/snapshot-controller/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  hack/addons/kustomize/aws-ccm/helm-values.yaml
  hack/addons/kustomize/aws-ebs-csi/helm-values.yaml
  hack/addons/kustomize/local-path-provisioner-csi/helm-values.yaml
  hack/addons/kustomize/nfd/helm-values.yaml
  pkg/handlers/generic/lifecycle/ccm/aws/handler_test.go
Labels: fix

#899 feat: Enable Hubble Relay in Cilium deployment via CAAPH
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/helm-addon-installation.yaml
  hack/addons/kustomize/cilium/helm-values.yaml
  pkg/handlers/generic/lifecycle/ccm/aws/handler.go
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/cni/cilium/handler.go
  pkg/handlers/generic/lifecycle/csi/awsebs/handler.go
  pkg/handlers/generic/lifecycle/csi/localpath/handler.go
  pkg/handlers/generic/lifecycle/csi/snapshotcontroller/handler.go
  test/e2e/clusterautoscaler_helpers.go
  test/e2e/cni_helpers.go
  test/e2e/framework/self_hosted.go
Labels: feature

#896 feat: Extract CAAPH values templates to files
  .pre-commit-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/ccm/aws/image-selection.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/ccm/aws/map-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/ccm/aws/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/ccm/nutanix/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/cluster-autoscaler/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/cni/calico/aws/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/cni/calico/docker/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/cni/calico/nutanix/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/cni/cilium/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/csi/aws-ebs/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/csi/local-path/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/csi/nutanix/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/csi/snapshot-controller/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/nfd/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/serviceloadbalancer/metallb/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/nutanix/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/aws/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/docker/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/nutanix/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/snapshot-controller/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/snapshot-controller/manifests/snapshot-controller-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/serviceloadbalancer/metallb/helm-addon-installation.yaml
  devbox.json
  devbox.lock
  hack/addons/kustomize/aws-ccm/kustomization.yaml.tmpl
  hack/addons/kustomize/aws-ebs-csi/kustomization.yaml.tmpl
  hack/addons/kustomize/cilium/helm-values.yaml
  hack/addons/kustomize/cilium/kustomization.yaml.tmpl
  hack/addons/kustomize/local-path-provisioner-csi/kustomization.yaml.tmpl
  hack/addons/kustomize/nfd/kustomization.yaml.tmpl
  hack/addons/kustomize/snapshot-controller/kustomization.yaml.tmpl
  hack/addons/kustomize/tigera-operator/helm-values.yaml
  hack/addons/kustomize/tigera-operator/kustomization.yaml.tmpl
  hack/addons/update-aws-ccm.sh
  hack/addons/update-aws-ebs-csi.sh
  hack/addons/update-cilium-manifests.sh
  hack/addons/update-cluster-autoscaler.sh
  hack/addons/update-local-path-provisioner-csi.sh
  hack/addons/update-node-feature-discovery-manifests.sh
  hack/addons/update-snapshot-controller.sh
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler_test.go
Labels: feature

#901 fix: Do not use digests for Cilium images
  charts/cluster-api-runtime-extensions-nutanix/addons/cni/cilium/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
Labels: fix

#904 fix: upgrade metallb to 0.14.8
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/serviceloadbalancer/metallb/helm-addon-installation.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: fix

#913 feat: Build with go 1.23.1
  api/go.mod
  common/go.mod
  go.mod
Labels: feature

#910 release(release/v0.14.x): v0.14.8
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#909 feat: Support node taints per nodepool and control plane
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_awsworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixnodeconfigs.yaml
  api/v1alpha1/nodeconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/addons/serviceloadbalancer.md
  docs/content/customization/generic/taints.md
  pkg/handlers/aws/mutation/metapatch_handler.go
  pkg/handlers/docker/mutation/metapatch_handler.go
  pkg/handlers/generic/handlers.go
  pkg/handlers/generic/mutation/handlers.go
  pkg/handlers/generic/mutation/metapatch_handler.go
  pkg/handlers/generic/mutation/taints/inject_controlplane.go
  pkg/handlers/generic/mutation/taints/inject_controlplane_test.go
  pkg/handlers/generic/mutation/taints/inject_suite_test.go
  pkg/handlers/generic/mutation/taints/inject_worker.go
  pkg/handlers/generic/mutation/taints/inject_worker_test.go
  pkg/handlers/generic/mutation/taints/variables_test.go
  pkg/handlers/nutanix/mutation/metapatch_handler.go
Labels: feature

#891 release(main): v0.16.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#916 feat: Support XValidations (CEL) for CC variables
  common/pkg/capi/clustertopology/variables/fromcrdyaml.go
Labels: feature

#917 feat: Update addon versions
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.3-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/tigera-operator-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/snapshot-controller/manifests/snapshot-controller-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/virtual-ip/kube-vip/manifests/kube-vip-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: feature

#922 release(main): v0.17.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/content/contributing/releasing.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#919 feat: Add feature-gates plumbing
  cmd/main.go
  pkg/features/feature_gates.go
Labels: feature
