Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-02, with the labels that each got.

#332 fix: Ensure registry credentials are namespace local to Cluster
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/tests/generate_patches.go
  pkg/handlers/generic/mutation/imageregistries/credentials/variables_test.go
  pkg/handlers/generic/mutation/mirrors/mirror.go
  pkg/handlers/generic/mutation/mirrors/mirror_test.go
  pkg/handlers/generic/mutation/mirrors/tests/generate_patches.go
  pkg/handlers/generic/mutation/mirrors/variables_test.go
Labels: fix

#348 fix: downgrade Calico to v3.26.4
  charts/capi-runtime-extensions/templates/cni/calico/manifests/tigera-operator-configmap.yaml
  devbox.json
  hack/flakes/flake.nix
  make/addons.mk
  pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
Labels: fix

#343 feat: Support multiple registry credentials if specified
  api/v1alpha1/clusterconfig_types.go
  common/go.mod
  common/go.sum
  common/pkg/k8s/client/fakessa/client.go
  common/pkg/testutils/capitest/patches.go
  common/pkg/testutils/capitest/request/items.go
  go.mod
  go.sum
  pkg/handlers/aws/mutation/metapatch_handler_test.go
  pkg/handlers/docker/mutation/metapatch_handler_test.go
  pkg/handlers/generic/mutation/httpproxy/systemd_proxy_config.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credentials_secret.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
  pkg/handlers/generic/mutation/imageregistries/credentials/templates/static-credential-provider.json.gotmpl
  pkg/handlers/generic/mutation/imageregistries/credentials/tests/generate_patches.go
  pkg/handlers/generic/mutation/imageregistries/credentials/variables_test.go
  pkg/handlers/generic/mutation/mirrors/mirror.go
Labels: feature

#345 fix: AMI ID patch
  .golangci.yml
  common/pkg/testutils/capitest/patches.go
  pkg/handlers/aws/mutation/ami/inject.go
  pkg/handlers/aws/mutation/ami/tests/generate_patches.go
Labels: fix

#344 fix: use correct AWS EBS CSI images
  charts/capi-runtime-extensions/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  hack/addons/kustomize/aws-ebs-csi/kustomization.yaml.tmpl
Labels: fix

#359 fix: mirror credentials support in DynamicCredentialProviderConfig
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
  pkg/handlers/generic/mutation/mirrors/mirror.go
Labels: fix

#365 fix: remove word konvoy/ and use cre/
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/tests/generate_patches.go
Labels: fix

#363 fix: v2/ in Containerd mirror path
  pkg/handlers/generic/mutation/mirrors/mirror.go
  pkg/handlers/generic/mutation/mirrors/mirror_test.go
  pkg/handlers/generic/mutation/mirrors/templates/hosts.toml.gotmpl
Labels: fix

#364 fix: set config_path in Containerd config
  pkg/handlers/generic/mutation/mirrors/inject.go
  pkg/handlers/generic/mutation/mirrors/mirror.go
  pkg/handlers/generic/mutation/mirrors/mirror_test.go
  pkg/handlers/generic/mutation/mirrors/templates/containerd-apply-patches.sh.gotmpl
  pkg/handlers/generic/mutation/mirrors/templates/containerd-registry-config-drop-in.toml
  pkg/handlers/generic/mutation/mirrors/tests/generate_patches.go
Labels: fix

#362 fix: generate config with only globalImageRegistryMirror set
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credentialprovider/matcher.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Labels: fix

#372 fix: revert back generated file changes
  api/v1alpha1/zz_generated.deepcopy.go
Labels: fix

#374 fix: restart Containerd when setting mirror config
  pkg/handlers/generic/mutation/mirrors/inject.go
  pkg/handlers/generic/mutation/mirrors/mirror.go
  pkg/handlers/generic/mutation/mirrors/templates/containerd-restart.sh
  pkg/handlers/generic/mutation/mirrors/tests/generate_patches.go
Labels: fix

#382 build: Remove dockerauth dependency
  make/goreleaser.mk
Labels: ignore-for-release

#392 build: Use kustomization.yaml from ESB CSI repo
  hack/addons/kustomize/aws-ebs-csi/kustomization.yaml.tmpl
Labels: ignore-for-release

#393 feat: Upgrade AWS ESB CSI and switch to using Helm chart
  charts/capi-runtime-extensions/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  hack/addons/kustomize/aws-cpi/kustomization.yaml.tmpl
  hack/addons/kustomize/aws-ebs-csi/helm-values.yaml
  hack/addons/kustomize/aws-ebs-csi/kustomization.yaml.tmpl
  hack/addons/kustomize/aws-ebs-csi/overlays/controller-priorityClassName.yaml
  hack/addons/kustomize/aws-ebs-csi/overlays/ds-priorityClassName.yaml
  hack/addons/kustomize/aws-ebs-csi/overlays/ds-tolerations.yaml
  hack/addons/kustomize/cilium/kustomization.yaml.tmpl
  hack/addons/kustomize/external-snapshotter/kustomization.yaml.tmpl
  hack/addons/kustomize/external-snapshotter/overlays/deployment-nodeAffinity.yaml
  hack/addons/kustomize/external-snapshotter/overlays/deployment-priorityClassName.yaml
  hack/addons/kustomize/nfd/kustomization.yaml.tmpl
  hack/addons/kustomize/tigera-operator/kustomization.yaml.tmpl
  hack/addons/update-aws-ebs-csi.sh
  make/addons.mk
Labels: feature

#391 test(e2e): Find specific CRS binding when checking if resource is applied
  test/e2e/clusterresourceset_helpers.go
Labels: ignore-for-release

#409 fix: Ensure addons defaults namespaces are correctly wired up
  charts/capi-runtime-extensions/templates/deployment.yaml
Labels: fix

#411 fix: Disbable hubble in Cilium deployment via CRS
  charts/capi-runtime-extensions/templates/cni/cilium/manifests/cilium-configmap.yaml
  hack/addons/kustomize/cilium/helm-values.yaml
Labels: fix

#413 fix: Fix Cilium helm values to use kubernetes IPAM
  charts/capi-runtime-extensions/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/capi-runtime-extensions/templates/cni/cilium/manifests/helm-addon-installation.yaml
  hack/addons/kustomize/cilium/helm-values.yaml
Labels: fix
