Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-05, with the labels that each got.

#598 fix: Fix error messages returned by HelmChartGetter
  pkg/handlers/generic/lifecycle/config/cm.go
Labels: fix

#592 feat: Add the ServiceLoadbalancer Addon, with MetalLB as first provider
  api/v1alpha1/addon_types.go
  api/v1alpha1/constants.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/serviceloadbalancer/metallb/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  docs/content/addons/serviceloadbalancer.md
  hack/addons/kustomize/metallb/kustomization.yaml.tmpl
  make/addons.mk
  pkg/handlers/aws/mutation/controlplaneloadbalancer/inject_test.go
  pkg/handlers/generic/lifecycle/config/cm.go
  pkg/handlers/generic/lifecycle/handlers.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
  pkg/handlers/generic/lifecycle/utils/utils.go
Labels: feature

#612 fix: use a consistent MachineDeployment class name
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/examples/bases/nutanix/cluster/kustomization.yaml.tmpl
  hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
Labels: fix

#611 fix: Do not return error if serviceLoadBalancer field is not set
  api/v1alpha1/addon_types.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
Labels: fix

#591 feat: adds GPU mutation
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixnodeconfigs.yaml
  api/v1alpha1/nutanix_node_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/customization/nutanix/machine-details.md
  pkg/handlers/nutanix/mutation/machinedetails/inject.go
  pkg/handlers/nutanix/mutation/machinedetails/inject_control_plane_test.go
Labels: feature

#625 build: Latest devbox update
  devbox.lock
  hack/flakes/flake.lock
  hack/flakes/flake.nix
Labels: ignore-for-release

#627 fix: use provided options for serverside apply
  common/pkg/k8s/client/apply.go
Labels: fix

#603 fix: Correct the CSI handler logic
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  common/pkg/capi/clustertopology/variables/json.go
  pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
  pkg/handlers/generic/lifecycle/csi/handler.go
  pkg/handlers/generic/lifecycle/csi/handler_test.go
  pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
  pkg/handlers/generic/lifecycle/utils/scs.go
Labels: fix

#607 fix: Fix the internal ClusterConfig type used for provider-agnostic logic
  pkg/common/clusterconfig/types.go
Labels: fix

#638 fix: Add DS_Store in the gitignore list
  .gitignore
Labels: fix

#649 fix: log mutation failure errors
  common/pkg/capi/clustertopology/patches/generator.go
Labels: fix

#644 fix: Always apply containerd patches
  pkg/handlers/generic/mutation/containerdapplypatchesandrestart/apply_patches.go
  pkg/handlers/generic/mutation/containerdapplypatchesandrestart/inject.go
  pkg/handlers/generic/mutation/containerdapplypatchesandrestart/inject_test.go
  pkg/handlers/generic/mutation/containerdapplypatchesandrestart/restart.go
  pkg/handlers/generic/mutation/containerdapplypatchesandrestart/templates/containerd-apply-patches.sh.gotmpl
  pkg/handlers/generic/mutation/containerdapplypatchesandrestart/templates/containerd-restart.sh
  pkg/handlers/generic/mutation/containerdrestart/inject_test.go
  pkg/handlers/generic/mutation/handlers.go
  pkg/handlers/generic/mutation/mirrors/inject.go
  pkg/handlers/generic/mutation/mirrors/inject_test.go
  pkg/handlers/generic/mutation/mirrors/mirror.go
  pkg/handlers/generic/mutation/mirrors/mirror_test.go
  pkg/handlers/generic/mutation/mirrors/templates/containerd-apply-patches.sh.gotmpl
Labels: fix

#658 fix: cluster-autoscaler Helm values for workload clusters
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/helm-addon-installation.yaml
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/template.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/template_test.go
Labels: fix

#648 fix: Make Cluster the owner of image registry credential secret
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Labels: fix

#645 feat: Enable unprivileged ports sysctl in containerd config
  pkg/handlers/generic/mutation/containerdunprivilegedports/files/unprivileged-ports-config.toml
  pkg/handlers/generic/mutation/containerdunprivilegedports/inject.go
  pkg/handlers/generic/mutation/containerdunprivilegedports/inject_test.go
  pkg/handlers/generic/mutation/containerdunprivilegedports/unprivileged_ports.go
  pkg/handlers/generic/mutation/handlers.go
Labels: feature

#610 feat: API for encryption at-rest
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_genericclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  common/pkg/k8s/client/create.go
  pkg/handlers/generic/mutation/encryptionatrest/encryptionprovider_test.go
  pkg/handlers/generic/mutation/encryptionatrest/inject.go
  pkg/handlers/generic/mutation/encryptionatrest/inject_test.go
  pkg/handlers/generic/mutation/encryptionatrest/tokengenerator.go
  pkg/handlers/generic/mutation/handlers.go
Labels: feature

#661 feat: Bump sigs.k8s.io/cluster-api to v1.7.2
  api/go.mod
  api/go.sum
  cluster-api-runtime-extensions-nutanix.code-workspace
  common/go.mod
  common/go.sum
  go.mod
  go.sum
  hack/flakes/flake.lock
  hack/flakes/flake.nix
  pkg/handlers/generic/lifecycle/clusterautoscaler/template.go
  test/e2e/e2e_suite_test.go
  test/e2e/ownerreference_helpers.go
  test/e2e/quick_start_test.go
Labels: feature

#676 feat: Pull calico images from quay.io instead of docker hub
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/aws/crs-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/aws/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/docker/crs-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/docker/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/nutanix/crs-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/nutanix/helm-addon-installation.yaml
Labels: feature

#677 fix: Upgrade dynamic-credential-provider to v0.5.3
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_install_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/templates/dynamic-credential-provider-config.yaml.gotmpl
Labels: fix

#681 feat: update cluster autoscaler to v1.30.0
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  make/addons.mk
Labels: feature

#597 release(main): v0.9.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#689 feat: Upgrade to Cilium v1.15.5
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/kustomize/cilium/helm-values.yaml
  make/addons.mk
Labels: feature

#691 feat: bumps caaph to v0.2.3
  api/external/sigs.k8s.io/cluster-api-addon-provider-helm/api/v1alpha1/condition_consts.go
  api/external/sigs.k8s.io/cluster-api-addon-provider-helm/api/v1alpha1/helmchartproxy_types.go
  api/external/sigs.k8s.io/cluster-api-addon-provider-helm/api/v1alpha1/helmreleaseproxy_types.go
  api/external/sigs.k8s.io/cluster-api-addon-provider-helm/api/v1alpha1/zz_generated.deepcopy.go
  hack/third-party/caaph/go.mod
  hack/third-party/caaph/go.sum
Labels: feature

#693 feat: Add local-path-provisioner CSI
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_genericclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  examples/capi-quick-start/docker-cluster-calico-crs.yaml
  examples/capi-quick-start/docker-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/docker-cluster-cilium-crs.yaml
  examples/capi-quick-start/docker-cluster-cilium-helm-addon.yaml
  hack/addons/kustomize/local-path-provisioner-csi/kustomization.yaml.tmpl
  hack/examples/bases/docker/cluster/kustomization.yaml.tmpl
  hack/examples/patches/docker/csi.yaml
  make/addons.mk
  pkg/handlers/generic/lifecycle/config/cm.go
  pkg/handlers/generic/lifecycle/csi/handler.go
  pkg/handlers/generic/lifecycle/csi/localpath/handler.go
  pkg/handlers/generic/lifecycle/handlers.go
Labels: feature
