Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-11, with the labels that each got.

#960 fix: Use correct filename for runtime extensions component YAML
  .gitignore
  .goreleaser.yml
  docs/content/getting-started/deployment/via-clusterctl.md
  test/e2e/config/caren.yaml
Labels: fix

#959 feat: set default CoreDNS version
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_genericclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  docs/content/customization/generic/dns.md
  examples/capi-quick-start/aws-cluster-calico-crs.yaml
  examples/capi-quick-start/aws-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/aws-cluster-cilium-crs.yaml
  examples/capi-quick-start/aws-cluster-cilium-helm-addon.yaml
  examples/capi-quick-start/docker-cluster-calico-crs.yaml
  examples/capi-quick-start/docker-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/docker-cluster-cilium-crs.yaml
  examples/capi-quick-start/docker-cluster-cilium-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/examples/bases/aws/cluster/kustomization.yaml.tmpl
  hack/examples/bases/docker/cluster/kustomization.yaml.tmpl
  hack/examples/bases/nutanix/cluster/kustomization.yaml.tmpl
  hack/examples/patches/coredns.yaml
  pkg/handlers/generic/mutation/coredns/inject.go
  pkg/handlers/generic/mutation/coredns/inject_test.go
  test/e2e/coredns_helpers.go
  test/e2e/quick_start_test.go
  test/e2e/self_hosted_test.go
Labels: feature

#962 release(main): v0.22.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#967 feat: Build with go 1.23.3 and upgrade all tools
  .github/workflows/checks.yml
  .pre-commit-config.yaml
  api/go.mod
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_awsworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_genericclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixnodeconfigs.yaml
  common/go.mod
  devbox.json
  devbox.lock
  go.mod
  hack/flakes/flake.lock
  hack/flakes/flake.nix
  make/kind.mk
Labels: feature

#972 fix: Update mindthegap to fix cert rotation
  hack/addons/mindthegap-helm-registry/Dockerfile
Labels: fix

#971 fix: Update mindthegap to fix cert rotation
  hack/addons/helm-chart-bundler/Dockerfile
Labels: fix

#974 release(release/v0.14.x): v0.14.10
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#927 fix: image registries with no credentials but with a CA
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Labels: fix

#973 release(main): v0.23.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#975 fix: set container name to manager to ensure we wait for it
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
Labels: fix

#976 release(main): v0.23.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#924 feat: Auto renewal of control plane certificates patch
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/controlplane_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixworkernodeconfigs.yaml
  api/v1alpha1/nodeconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/variables/aggregate_types.go
  docs/content/customization/generic/auto-renewal-of-control-plane-certs.md
  docs/content/customization/generic/encryption-at-rest.md
  pkg/handlers/aws/mutation/ami/variables_test.go
  pkg/handlers/aws/mutation/iaminstanceprofile/variables_test.go
  pkg/handlers/aws/mutation/instancetype/variables_test.go
  pkg/handlers/aws/mutation/securitygroups/variables_test.go
  pkg/handlers/docker/mutation/customimage/variables_test.go
  pkg/handlers/docker/workerconfig/variables.go
  pkg/handlers/docker/workerconfig/variables_test.go
  pkg/handlers/generic/mutation/autorenewcerts/inject.go
  pkg/handlers/generic/mutation/autorenewcerts/inject_test.go
  pkg/handlers/generic/mutation/handlers.go
  pkg/handlers/generic/mutation/taints/variables_test.go
  pkg/handlers/nutanix/mutation/machinedetails/variables_test.go
  pkg/handlers/nutanix/workerconfig/variables.go
  pkg/handlers/nutanix/workerconfig/variables_test.go
Labels: feature
