Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-04, with the labels that each got.

#504 fix: set defaults for AWS CP and Worker instanceType
  api/v1alpha1/aws_node_types.go
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/node_types.go
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
  hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
  pkg/handlers/aws/clusterconfig/variables.go
  pkg/handlers/aws/mutation/ami/variables_test.go
  pkg/handlers/aws/mutation/controlplaneloadbalancer/variables_test.go
  pkg/handlers/aws/mutation/iaminstanceprofile/variables_test.go
  pkg/handlers/aws/mutation/instancetype/variables_test.go
  pkg/handlers/aws/mutation/network/variables_test.go
  pkg/handlers/aws/mutation/region/variables_test.go
  pkg/handlers/aws/mutation/securitygroups/variables_test.go
  pkg/handlers/aws/workerconfig/variables.go
  pkg/handlers/aws/workerconfig/variables_test.go
Labels: fix

#506 feat: set default instance profile for AWS CP and worker nodes
  api/v1alpha1/aws_node_types.go
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
  hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
Labels: feature

#514 feat: give mutators a clusterGetter function
  cmd/main.go
  common/pkg/capi/clustertopology/handlers/mutation/meta.go
  common/pkg/capi/clustertopology/handlers/mutation/meta_test.go
  pkg/handlers/aws/mutation/ami/inject.go
  pkg/handlers/aws/mutation/ami/inject_control_plane_test.go
  pkg/handlers/aws/mutation/ami/inject_worker_test.go
  pkg/handlers/aws/mutation/cni/calico/inject.go
  pkg/handlers/aws/mutation/cni/calico/inject_test.go
  pkg/handlers/aws/mutation/controlplaneloadbalancer/inject.go
  pkg/handlers/aws/mutation/controlplaneloadbalancer/inject_test.go
  pkg/handlers/aws/mutation/iaminstanceprofile/inject_control_plane.go
  pkg/handlers/aws/mutation/iaminstanceprofile/inject_control_plane_test.go
  pkg/handlers/aws/mutation/iaminstanceprofile/inject_worker.go
  pkg/handlers/aws/mutation/iaminstanceprofile/inject_worker_test.go
  pkg/handlers/aws/mutation/instancetype/inject_control_plane.go
  pkg/handlers/aws/mutation/instancetype/inject_control_plane_test.go
  pkg/handlers/aws/mutation/instancetype/inject_worker.go
  pkg/handlers/aws/mutation/instancetype/inject_worker_test.go
  pkg/handlers/aws/mutation/metapatch_handler.go
  pkg/handlers/aws/mutation/network/inject.go
  pkg/handlers/aws/mutation/network/inject_test.go
  pkg/handlers/aws/mutation/region/inject.go
  pkg/handlers/aws/mutation/region/inject_test.go
  pkg/handlers/aws/mutation/securitygroups/inject.go
  pkg/handlers/aws/mutation/securitygroups/inject_control_plane_test.go
  pkg/handlers/aws/mutation/securitygroups/inject_worker_test.go
  pkg/handlers/docker/mutation/customimage/inject_control_plane.go
  pkg/handlers/docker/mutation/customimage/inject_control_plane_test.go
  pkg/handlers/docker/mutation/customimage/inject_worker.go
  pkg/handlers/docker/mutation/customimage/inject_worker_test.go
  pkg/handlers/docker/mutation/metapatch_handler.go
  pkg/handlers/generic/mutation/auditpolicy/inject.go
  pkg/handlers/generic/mutation/auditpolicy/inject_test.go
  pkg/handlers/generic/mutation/containerdmetrics/inject.go
  pkg/handlers/generic/mutation/containerdmetrics/inject_test.go
  pkg/handlers/generic/mutation/containerdrestart/inject.go
  pkg/handlers/generic/mutation/containerdrestart/inject_test.go
  pkg/handlers/generic/mutation/etcd/inject.go
  pkg/handlers/generic/mutation/etcd/inject_test.go
  pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
  pkg/handlers/generic/mutation/extraapiservercertsans/inject_test.go
  pkg/handlers/generic/mutation/httpproxy/inject.go
  pkg/handlers/generic/mutation/httpproxy/inject_test.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
  pkg/handlers/generic/mutation/kubernetesimagerepository/inject.go
  pkg/handlers/generic/mutation/kubernetesimagerepository/inject_test.go
  pkg/handlers/generic/mutation/mirrors/inject.go
  pkg/handlers/generic/mutation/mirrors/inject_test.go
  pkg/handlers/generic/mutation/users/inject.go
  pkg/handlers/generic/mutation/users/inject_test.go
  pkg/handlers/nutanix/mutation/controlplaneendpoint/inject.go
  pkg/handlers/nutanix/mutation/controlplaneendpoint/inject_test.go
  pkg/handlers/nutanix/mutation/machinedetails/inject.go
  pkg/handlers/nutanix/mutation/machinedetails/inject_control_plane_test.go
  pkg/handlers/nutanix/mutation/machinedetails/inject_worker_test.go
  pkg/handlers/nutanix/mutation/metapatch_handler.go
  pkg/handlers/nutanix/mutation/prismcentralendpoint/inject.go
  pkg/handlers/nutanix/mutation/prismcentralendpoint/inject_test.go
  test/helpers/envtest.go
Labels: feature

#520 ci: Add permissions to add PR review comments for reviewdog actions
  .github/workflows/checks.yml
Labels: ignore-for-release

#524 fix: add omitempty to CCM Credentials struct
  api/v1alpha1/addon_types.go
Labels: fix

#528 ci: Allow release as a PR type
  .github/workflows/conventional-pr-title.yml
Labels: ignore-for-release

#519 feat: get default sans via cluster object in patch handler for docker
  api/v1alpha1/clusterconfig_types.go
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
  common/pkg/capi/utils/utils.go
  hack/examples/bases/docker/clusterclass/kustomization.yaml.tmpl
  pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
  pkg/handlers/generic/mutation/extraapiservercertsans/inject_test.go
Labels: feature

#522 feat: adds nutanix SANs via patchHandler
  api/v1alpha1/clusterconfig_types.go
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
  pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
  pkg/handlers/generic/mutation/extraapiservercertsans/inject_test.go
Labels: feature

#532 fix: Add specific descriptions to Nutanix machine details fields
  api/v1alpha1/nutanix_node_types.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: fix

#531 feat: nutanix csi driver 3.0
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/nutanix-storage-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/addons/kustomize/nutanix-storage-csi/helm-values.yaml
  hack/addons/kustomize/nutanix-storage-csi/kustomization.yaml.tmpl
  hack/addons/update-nutanix-csi.sh
  hack/examples/additional-resources/nutanix/csi-secret.yaml
  hack/examples/patches/nutanix/csi.yaml
  make/addons.mk
Labels: feature

#525 feat: Add additionalCategories field to Nutanix machine details patch
  api/v1alpha1/nutanix_node_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/customization/nutanix/machine-details.md
  pkg/handlers/nutanix/mutation/machinedetails/inject.go
  pkg/handlers/nutanix/mutation/machinedetails/inject_control_plane_test.go
  pkg/handlers/nutanix/mutation/machinedetails/variables_test.go
Labels: feature

#555 feat: Upgrade to CAPI v1.7.0
  api/go.mod
  api/go.sum
  api/v1alpha1/nutanix_node_types.go
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
  common/go.mod
  common/go.sum
  common/pkg/capi/clustertopology/patches/matchers/match.go
  common/pkg/capi/clustertopology/variables/variable.go
  common/pkg/capi/clustertopology/variables/variables_test.go
  devbox.json
  devbox.lock
  go.mod
  go.sum
  hack/flakes/flake.nix
  pkg/handlers/aws/mutation/ami/inject.go
  pkg/handlers/aws/mutation/cni/calico/inject.go
  pkg/handlers/aws/mutation/controlplaneloadbalancer/inject.go
  pkg/handlers/aws/mutation/iaminstanceprofile/inject_control_plane.go
  pkg/handlers/aws/mutation/iaminstanceprofile/inject_worker.go
  pkg/handlers/aws/mutation/instancetype/inject_control_plane.go
  pkg/handlers/aws/mutation/instancetype/inject_worker.go
  pkg/handlers/aws/mutation/network/inject.go
  pkg/handlers/aws/mutation/region/inject.go
  pkg/handlers/aws/mutation/securitygroups/inject.go
  pkg/handlers/docker/mutation/customimage/inject_control_plane.go
  pkg/handlers/docker/mutation/customimage/inject_worker.go
  pkg/handlers/generic/lifecycle/ccm/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/handler.go
  pkg/handlers/generic/lifecycle/cni/calico/handler.go
  pkg/handlers/generic/lifecycle/cni/cilium/handler.go
  pkg/handlers/generic/lifecycle/csi/handler.go
  pkg/handlers/generic/lifecycle/nfd/handler.go
  pkg/handlers/generic/mutation/etcd/inject.go
  pkg/handlers/generic/mutation/extraapiservercertsans/inject.go
  pkg/handlers/generic/mutation/httpproxy/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/kubernetesimagerepository/inject.go
  pkg/handlers/generic/mutation/mirrors/inject.go
  pkg/handlers/generic/mutation/users/inject.go
  pkg/handlers/nutanix/mutation/controlplaneendpoint/inject.go
  pkg/handlers/nutanix/mutation/machinedetails/inject.go
  pkg/handlers/nutanix/mutation/prismcentralendpoint/inject.go
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/quick_start_test.go
Labels: feature

#560 feat: CAPI v1.7.1
  api/go.mod
  api/go.sum
  common/go.mod
  common/go.sum
  go.mod
  go.sum
  hack/flakes/flake.nix
Labels: feature

#556 feat: Preserve user-managed fields when applying resources
  common/pkg/k8s/client/apply.go
  pkg/handlers/generic/lifecycle/ccm/aws/handler.go
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
  pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
  pkg/handlers/generic/lifecycle/nfd/strategy_crs.go
  pkg/handlers/generic/lifecycle/nfd/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/utils/scs.go
  pkg/handlers/generic/lifecycle/utils/secrets.go
  pkg/handlers/generic/lifecycle/utils/utils.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
Labels: feature

#523 feat: Added e2e test for capx cluster
  .github/workflows/e2e.yml
  pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-capx/metadata.yaml
  test/e2e/ownerreference_helpers.go
  test/e2e/quick_start_test.go
Labels: feature

#558 feat: add kube-vip static Pod in a Nutanix handler
  api/v1alpha1/common_types.go
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/virtual-ip/kube-vip/manifests/kube-vip-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  docs/content/customization/nutanix/control-plane-endpoint.md
  examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/addons/update-kube-vip-manifests.sh
  hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
  hack/examples/patches/nutanix/initialize-variables.yaml
  make/addons.mk
  pkg/handlers/generic/mutation/controlplanevirtualip/inject.go
  pkg/handlers/generic/mutation/controlplanevirtualip/inject_test.go
  pkg/handlers/generic/mutation/controlplanevirtualip/providers/kubevip.go
  pkg/handlers/generic/mutation/controlplanevirtualip/providers/kubevip_test.go
  pkg/handlers/generic/mutation/controlplanevirtualip/providers/providers.go
  pkg/handlers/nutanix/handlers.go
  pkg/handlers/nutanix/mutation/controlplaneendpoint/inject.go
  pkg/handlers/nutanix/mutation/controlplanevirtualip/inject.go
  pkg/handlers/nutanix/mutation/metapatch_handler.go
  pkg/handlers/options/global.go
Labels: feature

#527 release(main): v0.8.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#593 release(main): v0.8.1
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#594 feat: expose GenerateNoProxy func
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/http_proxy.go
  api/v1alpha1/http_proxy_test.go
  pkg/handlers/generic/mutation/httpproxy/inject.go
  pkg/handlers/generic/mutation/httpproxy/inject_test.go
  pkg/handlers/generic/mutation/httpproxy/systemd_proxy_config.go
  pkg/handlers/generic/mutation/httpproxy/systemd_proxy_config_test.go
Labels: feature
