Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-06, with the labels that each got.

#698 fix: use external Nutanix API types directly
  api/v1alpha1/nutanix_node_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/handlers/nutanix/mutation/machinedetails/inject_control_plane_test.go
  pkg/handlers/nutanix/mutation/machinedetails/variables_test.go
Labels: fix

#711 fix: nutanix credentials Secrets owner refs
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
  pkg/handlers/generic/lifecycle/utils/secrets.go
  pkg/handlers/generic/lifecycle/utils/secrets_test.go
Labels: fix

#709 fix: credential provider response secret ownership
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
Labels: fix

#714 feat: cluster-api v1.7.3
  api/go.mod
  api/go.sum
  api/v1alpha1/zz_generated.deepcopy.go
  common/go.mod
  common/go.sum
  go.mod
  go.sum
  hack/flakes/flake.nix
Labels: feature

#718 feat: bumps caaph to 0.2.4
  hack/third-party/caaph/go.mod
  hack/third-party/caaph/go.sum
Labels: feature

#715 feat: Controller that copies ClusterClasses to namespaces
  .pre-commit-config.yaml
  api/v1alpha1/constants.go
  charts/cluster-api-runtime-extensions-nutanix/templates/role.yaml
  cmd/main.go
  go.mod
  internal/test/README.md
  internal/test/bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  internal/test/bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  internal/test/builder/bootstrap.go
  internal/test/builder/builders.go
  internal/test/builder/controlplane.go
  internal/test/builder/crds.go
  internal/test/builder/doc.go
  internal/test/builder/infrastructure.go
  internal/test/builder/remediation.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/test/config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  internal/test/config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  internal/test/config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  internal/test/config/crd/bases/cluster.x-k8s.io_clusters.yaml
  internal/test/config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  internal/test/config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  internal/test/config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  internal/test/config/crd/bases/cluster.x-k8s.io_machines.yaml
  internal/test/config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  internal/test/config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  internal/test/config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  internal/test/config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  internal/test/controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  internal/test/controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  internal/test/envtest/environment.go
  internal/test/envtest/external.go
  pkg/controllers/namespacesync/controller.go
  pkg/controllers/namespacesync/controller_test.go
  pkg/controllers/namespacesync/copy.go
  pkg/controllers/namespacesync/copy_test.go
  pkg/controllers/namespacesync/doc.go
  pkg/controllers/namespacesync/flags.go
  pkg/controllers/namespacesync/references.go
  pkg/controllers/namespacesync/suite_test.go
Labels: feature

#637 feat: adds a mindthegap container and deployment
  .github/workflows/checks.yml
  .goreleaser.yml
  .pre-commit-config.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  devbox.lock
  hack/addons/generate-mindthegap-repofile.sh
  hack/addons/mindthegap-helm-registry/Dockerfile
  hack/addons/mindthegap-helm-registry/repos.yaml
  hack/tools/mindthegap-helm-reg/main.go
  make/addons.mk
  make/dev.mk
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/csi/localpath/handler.go
  pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
  pkg/handlers/generic/lifecycle/nfd/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
  pkg/handlers/generic/lifecycle/utils/utils.go
  test/e2e/config/caren.yaml
Labels: feature

#720 fix: set ownerReference on imageRegistry and globalMirror Secrets
  pkg/handlers/generic/lifecycle/ccm/aws/handler.go
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
  pkg/handlers/generic/lifecycle/csi/localpath/handler.go
  pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
  pkg/handlers/generic/lifecycle/nfd/strategy_crs.go
  pkg/handlers/generic/lifecycle/nfd/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
  pkg/handlers/utils/scs.go
  pkg/handlers/utils/scs_test.go
  pkg/handlers/utils/secrets.go
  pkg/handlers/utils/secrets_test.go
  pkg/handlers/utils/utils.go
  pkg/handlers/utils/utils_integration_test.go
  pkg/handlers/utils/utils_suite_test.go
  pkg/handlers/utils/utils_test.go
Labels: fix

#723 fix: Allow Nutanix CSI snapshot controller & webhook to run on CP nodes
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
Labels: fix

#724 fix: CredentialProviderConfig matchImages to support registries with port
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files_test.go
  pkg/handlers/generic/mutation/imageregistries/credentials/templates/kubelet-image-credential-provider-config.yaml.gotmpl
Labels: fix

#682 feat: implements BeforeClusterUpgrade hook
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  common/pkg/server/server.go
  hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/docker/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/nutanix/kustomization.yaml.tmpl
  pkg/handlers/generic/lifecycle/ccm/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/calico/handler.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/cilium/handler.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/csi/aws-ebs/handler.go
  pkg/handlers/generic/lifecycle/csi/handler.go
  pkg/handlers/generic/lifecycle/csi/handler_test.go
  pkg/handlers/generic/lifecycle/csi/localpath/handler.go
  pkg/handlers/generic/lifecycle/csi/nutanix-csi/handler.go
  pkg/handlers/generic/lifecycle/nfd/handler.go
  pkg/handlers/generic/lifecycle/nfd/strategy_crs.go
  pkg/handlers/generic/lifecycle/nfd/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
Labels: feature

#722 fix: Allow Node Feature Discovery garbage collector to run on control-plane nodes
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
  hack/addons/kustomize/nfd/helm-values.yaml
Labels: fix

#729 fix: image registries not handling CA certificates
  api/v1alpha1/constants.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/customization/generic/image-registries.md
  pkg/handlers/generic/mutation/imageregistries/constants.go
  pkg/handlers/generic/mutation/imageregistries/credentials/credential_provider_config_files.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject_test.go
  pkg/handlers/generic/mutation/mirrors/constants.go
  pkg/handlers/generic/mutation/mirrors/containerd_files.go
  pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
  pkg/handlers/generic/mutation/mirrors/inject.go
  pkg/handlers/generic/mutation/mirrors/inject_test.go
  pkg/handlers/generic/mutation/mirrors/mirror.go
  pkg/handlers/generic/mutation/mirrors/mirror_test.go
  pkg/handlers/generic/mutation/mirrors/templates/hosts.toml.gotmpl
  pkg/handlers/utils/secrets.go
Labels: fix

#741 fix: adds a docker buildx step before release-snapshot
  .github/workflows/checks.yml
  .github/workflows/e2e.yml
  .github/workflows/release-tag.yml
  .goreleaser.yml
  make/goreleaser.mk
Labels: fix

#685 release(main): v0.10.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#725 fix: Namespace Sync controller should list no resources when source namespace is empty string
  pkg/controllers/namespacesync/controller.go
  pkg/controllers/namespacesync/controller_test.go
  pkg/controllers/namespacesync/label.go
  pkg/controllers/namespacesync/label_test.go
Labels: fix

#751 fix: Temporarily hard-code supported PC version for Nutanix CSI
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/nutanix/manifests/helm-addon-installation.yaml
Labels: fix

#748 feat: Update AWS CCM versions and add HelmAddon strategy
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.27.7-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.28.6-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.29.3-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.1-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.schema.json
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  devbox.json
  devbox.lock
  examples/capi-quick-start/aws-cluster-calico-crs.yaml
  examples/capi-quick-start/aws-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/aws-cluster-cilium-crs.yaml
  examples/capi-quick-start/aws-cluster-cilium-helm-addon.yaml
  hack/addons/kustomize/aws-ccm/helm-values.yaml
  hack/addons/kustomize/aws-ccm/kustomization.yaml.tmpl
  hack/addons/mindthegap-helm-registry/repos.yaml
  hack/addons/update-aws-ccm.sh
  hack/examples/overlays/clusters/aws/calico/crs/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/aws/calico/helm-addon/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/aws/cilium/crs/kustomization.yaml.tmpl
  hack/examples/overlays/clusters/aws/cilium/helm-addon/kustomization.yaml.tmpl
  hack/examples/patches/aws/crs-strategy.yaml
  hack/examples/patches/aws/helm-addon-strategy.yaml
  hack/tools/helm-cm/main.go
  make/addons.mk
  make/dev.mk
  pkg/handlers/generic/lifecycle/ccm/aws/handler.go
  pkg/handlers/generic/lifecycle/ccm/aws/handler_test.go
  pkg/handlers/generic/lifecycle/ccm/aws/strategy_crs.go
  pkg/handlers/generic/lifecycle/config/cm.go
  pkg/handlers/generic/lifecycle/handlers.go
  test/e2e/addon_helpers.go
  test/e2e/ccm_helpers.go
  test/e2e/quick_start_test.go
  test/e2e/self_hosted_test.go
Labels: feature

#752 fix: skip kubeadm CA file when Secret doesn't have a CA
  pkg/handlers/generic/mutation/mirrors/containerd_files.go
  pkg/handlers/generic/mutation/mirrors/inject.go
  pkg/handlers/generic/mutation/mirrors/inject_test.go
Labels: fix

#759 fix: Correctly report failed deploy of ServiceLoadBalancer
  pkg/handlers/generic/lifecycle/serviceloadbalancer/handler.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/handler_test.go
Labels: fix

#747 release(main): v0.11.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#761 release(main): v0.11.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending, autorelease: tagged
