Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-08, with the labels that each got.

#838 fix: sets uefi boot type
  examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/examples/patches/nutanix/initialize-variables.yaml
Labels: fix

#834 release(main): v0.13.5
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#842 fix: run systemctl daemon-reload before Containerd restart
  pkg/handlers/generic/mutation/containerdapplypatchesandrestart/templates/containerd-restart.sh
Labels: fix

#844 release(main): v0.13.6
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#847 fix: Deterministic ordering of lifecycle hooks
  common/go.mod
  common/pkg/capi/clustertopology/handlers/lifecycle/interfaces.go
  common/pkg/capi/clustertopology/handlers/lifecycle/ordered.go
  pkg/handlers/generic/lifecycle/handlers.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
Labels: fix

#848 fix: reorder lifecycle handlers with serviceloadbalancer being last
  pkg/handlers/generic/lifecycle/handlers.go
Labels: fix

#852 fix: update mindthegap
  hack/addons/mindthegap-helm-registry/Dockerfile
Labels: fix

#845 fix: Handle long cluster names
  .golangci.yml
  api/v1alpha1/constants.go
  charts/cluster-api-runtime-extensions-nutanix/templates/admission-service.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/certificates.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/role.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/runtimehooks-service.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/webhooks.yaml
  cmd/main.go
  devbox.json
  devbox.lock
  hack/addons/kustomize/cluster-autoscaler/helm-values.yaml
  hack/addons/kustomize/cluster-autoscaler/kustomization.yaml.tmpl
  hack/addons/update-cluster-autoscaler.sh
  hack/update-webhook-configurations.yq
  internal/test/envtest/environment.go
  make/go.mk
  pkg/handlers/generic/lifecycle/addons/helmaddon.go
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler_test.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/handler.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_crs.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/template.go
  pkg/handlers/generic/lifecycle/clusterautoscaler/template_test.go
  pkg/handlers/generic/lifecycle/cni/calico/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/cni/cilium/handler.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_crs.go
  pkg/handlers/generic/lifecycle/cni/cilium/strategy_helmaddon.go
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
  pkg/webhook/cluster/clusteruuidlabeler.go
  pkg/webhook/cluster/defaulter.go
  pkg/webhook/cluster/doc.go
  pkg/webhook/cluster/vaiidator.go
  pkg/webhook/cluster/webhook_suite_test.go
  pkg/webhook/cluster/webhook_test.go
  test/e2e/addon_helpers.go
  test/e2e/ccm_helpers.go
  test/e2e/clusterautoscaler_helpers.go
  test/e2e/cni_helpers.go
  test/e2e/csi_helpers.go
  test/e2e/framework/self_hosted.go
  test/e2e/helmreleaseproxy_helpers.go
  test/e2e/nfd_helpers.go
  test/e2e/quick_start_test.go
  test/e2e/self_hosted_test.go
  test/e2e/serviceloadbalancer_helpers.go
Labels: fix

#854 release(main): v0.13.7
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#856 fix: Cilium-Istio compatibility fixes
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/helm-addon-installation.yaml
  hack/addons/kustomize/cilium/helm-values.yaml
Labels: fix

#855 feat: Run hooks in parallel with aggregated responses
  api/go.mod
  common/go.mod
  common/go.sum
  common/pkg/capi/clustertopology/handlers/lifecycle/ordered.go
  common/pkg/capi/clustertopology/handlers/lifecycle/parallel.go
  common/pkg/capi/clustertopology/handlers/lifecycle/parallel_test.go
  go.mod
  go.sum
  hack/third-party/caaph/go.mod
  hack/third-party/capa/go.mod
  pkg/handlers/generic/lifecycle/handlers.go
Labels: feature

#858 release(main): v0.14.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#859 fix: delete correct cluster-autoscaler HCP
  pkg/handlers/generic/lifecycle/clusterautoscaler/strategy_helmaddon.go
Labels: fix

#860 fix: skip UUID annotation webhook for clusters with nil topology
  internal/test/envtest/environment.go
  pkg/webhook/cluster/clusteruuidlabeler.go
  pkg/webhook/cluster/webhook_suite_test.go
  pkg/webhook/cluster/webhook_test.go
Labels: fix

#862 release(main): v0.14.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#864 fix: Ensure ClusterAutoscaler can write status CM in workload cluster
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/helm-addon-installation.yaml
  hack/addons/kustomize/cluster-autoscaler/helm-values.yaml
Labels: fix

#866 release(main): v0.14.2
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#867 fix: CRS generated CA Deployment has extra quotes
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  hack/addons/update-cluster-autoscaler.sh
  test/e2e/clusterautoscaler_helpers.go
  test/e2e/configmap_helpers.go
Labels: fix

#871 fix: Use same security context & priority class for helm-repository pod
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
Labels: fix

#872 release(main): v0.14.3
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#877 release(main): v0.14.5
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#878 feat: Upgrade to Calico v3.28.1
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/tigera-operator-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: feature, do not merge

#881 fix: Filter out control plane endpoint from Nutanix node IPs
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/nutanix/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler_test.go
Labels: fix

#882 fix: [BACKPORT v0.14] Filter out control plane endpoint from Nutanix node IPs
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/nutanix/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler_test.go
Labels: fix

#883 release(release/v0.14.x): v0.14.6
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#887 release(main): v0.15.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#889 feat: Build with go 1.23
  .goreleaser.yml
  api/go.mod
  api/v1alpha1/nutanix_clusterconfig_types.go
  common/go.mod
  devbox.json
  devbox.lock
  go.mod
  hack/flakes/flake.lock
  hack/flakes/flake.nix
  hack/third-party/capx/go.mod
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/nutanix/mutation/prismcentralendpoint/inject.go
Labels: feature

#890 feat: Upgrade to Calico v3.28.1
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/tigera-operator-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: feature

#879 feat: Update all addon versions
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.27.9-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.28.9-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.29.6-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.2-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/virtual-ip/kube-vip/manifests/kube-vip-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  hack/addons/update-aws-ccm.sh
  make/addons.mk
Labels: feature
