Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2024-10, with the labels that each got.

#930 fix: Shorten readiness probe period to try to prevent races
  charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
Labels: fix

#933 fix: [release/v0.14.x] Rename webhook container to manager
  charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
Labels: fix

#936 release(release/v0.14.x): v0.14.9
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#939 feat(api): Add kubernetes version to coredns version mapping
  .pre-commit-config.yaml
  api/go.mod
  api/versions/coredns.go
  api/versions/coredns_test.go
  hack/tools/coredns-versions/main.go
  hack/tools/go.mod
  hack/tools/go.sum
  make/apis.mk
Labels: feature

#943 fix: list correct registry.k8s.io/sig-storage/csi-snapshotter image
  hack/tools/fetch-images/main.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: fix

#940 fix: include kube-vip image in generated caren-images.txt
  hack/tools/fetch-images/main.go
  make/addons.mk
Labels: fix

#944 release(main): v0.18.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
Labels: autorelease: pending

#947 feat: copy charts to pvc
  .goreleaser.yml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
  hack/addons/mindthegap-helm-registry/Dockerfile
Labels: feature

#948 release(main): v0.19.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#950 feat: support configuring CoreDNS image
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/constants.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_genericclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/customization/generic/dns.md
  docs/content/customization/generic/etcd.md
  pkg/handlers/generic/mutation/coredns/inject.go
  pkg/handlers/generic/mutation/coredns/inject_test.go
  pkg/handlers/generic/mutation/coredns/variables_test.go
  pkg/handlers/generic/mutation/handlers.go
Labels: feature

#953 release(main): v0.20.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#954 fix: bundle correct arch for the mindthegap binary
  hack/addons/mindthegap-helm-registry/Dockerfile
Labels: fix

#956 feat: update Nutanix CSI to 3.1.0
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: feature

#955 fix: use correct securityContext for Alpine based helm-repository Pod
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.schema.json
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
Labels: fix

#957 release(main): v0.21.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending
