Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2025-02, with the labels that each got.

#1022 fix: use republished COSI controller image
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: fix

#1033 feat: implementation for user defined configmap for cilium addon in cluster creation
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  docs/content/addons/cni.md
  pkg/handlers/generic/lifecycle/cni/cilium/handler.go
  pkg/handlers/generic/lifecycle/cni/variables_test.go
Labels: feature

#1010 feat: update CAPI to v1.9.3
  api/go.mod
  api/go.sum
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
  common/go.mod
  common/go.sum
  devbox.lock
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/controllers/namespacesync/references.go
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: feature

#1034 feat: adds cluster's ownerref on cilium helm values source object
  docs/content/addons/cni.md
  pkg/handlers/generic/lifecycle/ccm/nutanix/handler.go
  pkg/handlers/generic/lifecycle/cni/cilium/handler.go
  pkg/handlers/generic/lifecycle/csi/nutanix/handler.go
  pkg/handlers/generic/mutation/imageregistries/credentials/inject.go
  pkg/handlers/utils/secrets.go
  pkg/handlers/utils/secrets_test.go
Labels: feature

#1030 release(main): v0.26.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#1041 fix: Specify PriorityClass for Node Feature Discovery components
  charts/cluster-api-runtime-extensions-nutanix/addons/nfd/values-template.yaml
Labels: fix

#1045 fix: Configure priorityClassName for Cilium Hubble
  charts/cluster-api-runtime-extensions-nutanix/addons/cni/cilium/values-template.yaml
Labels: fix

#1042 fix: don't generate empty _default containerd mirror file
  pkg/handlers/generic/mutation/mirrors/containerd_files.go
  pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
  pkg/handlers/generic/mutation/mirrors/inject_test.go
Labels: fix

#1046 fix: set priority class name for metallb
  charts/cluster-api-runtime-extensions-nutanix/addons/serviceloadbalancer/metallb/values-template.yaml
Labels: fix

#1043 feat: Update COSI controller Addon
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: feature

#1047 feat: Build with Go 1.24.0
  .github/workflows/checks.yml
  .pre-commit-config.yaml
  api/go.mod
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_awsworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_genericclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixworkernodeconfigs.yaml
  common/go.mod
  devbox.json
  devbox.lock
  docs/content/customization/generic/encryption-at-rest.md
  go.mod
  hack/flakes/flake.lock
  hack/flakes/flake.nix
Labels: feature

#1048 release(main): v0.27.0
  .golangci.yml
  .release-please-manifest.json
  CHANGELOG.md
  docs/content/contributing/releasing.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#1021 fix(deps): Update Nutanix CCM Version
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/mindthegap-helm-registry/repos.yaml
  make/addons.mk
Labels: fix

#1049 fix(deps): Update Nutanix CCM Version (#1016)
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: fix

#1054 feat: Update all addon versions
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.27.10-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.28.10-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.32.0-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/tigera-operator-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/local-path-provisioner-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/snapshot-controller/manifests/snapshot-controller-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/virtual-ip/kube-vip/manifests/kube-vip-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.schema.json
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: feature

#1056 fix: update Cilium version to 1.16.7
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: fix

#1058 fix: release 0.27 devbox changes
  devbox.lock
Labels: fix
