Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2025-06, with the labels that each got.

#1137 feat: CIS benchmark improvements
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/docker/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/nutanix/kustomization.yaml.tmpl
  hack/examples/patches/cis-admissionconfiguration.yaml
  hack/examples/patches/cis-kubeadmconfigtemplate-kubelet-file-permissions.yaml
  hack/examples/patches/cis-kubeadmconfigtemplate.yaml
  hack/examples/patches/cis-kubeadmcontrolplanetemplate-kubelet-file-permissions.yaml
  hack/examples/patches/cis-kubeadmcontrolplanetemplate.yaml
  hack/examples/patches/disable-kubeadmcontrolplane-profiling.yaml
  hack/examples/patches/initialize-extravolumes.yaml
  hack/examples/patches/initialize-files.yaml
  hack/examples/patches/initialize-kubeadmconfigtemplate-postkubeadmcommands.yaml
  hack/examples/patches/initialize-kubeadmcontrolplanetemplate-postkubeadmcommands.yaml
  pkg/handlers/generic/mutation/auditpolicy/inject.go
  pkg/handlers/generic/mutation/auditpolicy/inject_test.go
Labels: feature

#1144 feat: update handler version
  README.md
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  docs/content/getting-started/integrating-with-your-clusterclass/_index.md
  hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/docker/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/nutanix/kustomization.yaml.tmpl
  pkg/handlers/aws/handlers.go
  pkg/handlers/aws/mutation/metapatch_handler.go
  pkg/handlers/docker/handlers.go
  pkg/handlers/docker/mutation/metapatch_handler.go
  pkg/handlers/generic/handlers.go
  pkg/handlers/generic/mutation/metapatch_handler.go
  pkg/handlers/nutanix/handlers.go
  pkg/handlers/nutanix/mutation/metapatch_handler.go
  pkg/handlers/v2/generic/mutation/controlplanevirtualip/inject.go
  pkg/handlers/v2/generic/mutation/controlplanevirtualip/inject_test.go
  pkg/handlers/v2/generic/mutation/controlplanevirtualip/providers/kubevip.go
  pkg/handlers/v2/generic/mutation/controlplanevirtualip/providers/kubevip_test.go
  pkg/handlers/v2/generic/mutation/controlplanevirtualip/providers/providers.go
  pkg/handlers/v2/generic/mutation/controlplanevirtualip/providers/templates/configure-for-kube-vip.sh
  pkg/handlers/v2/nutanix/mutation/controlplanevirtualip/inject.go
  pkg/handlers/v3/aws/mutation/metapatch_handler.go
  pkg/handlers/v3/docker/mutation/metapatch_handler.go
  pkg/handlers/v3/generic/mutation/handlers.go
  pkg/handlers/v3/generic/mutation/metapatch_handler.go
  pkg/handlers/v3/nutanix/mutation/metapatch_handler.go
Labels: feature

#1145 release(main): v0.29.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#1150 fix: update CNCF registry version to 2.3.4, app version 2.8.3
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  hack/addons/kustomize/cncf-distribution-registry/kustomization.yaml.tmpl
Labels: fix

#1152 release(release/v0.27.x): v0.27.5
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#1158 feat: add requests and limits to registry containers
  charts/cluster-api-runtime-extensions-nutanix/addons/registry/cncf-distribution/values-template.yaml
Labels: feature

#1159 fix: registry addon headless service port
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  hack/addons/kustomize/cncf-distribution-registry/kustomization.yaml.tmpl
Labels: fix

#1156 feat: Preflight check opt-out
  pkg/webhook/preflight/preflight.go
  pkg/webhook/preflight/preflight_test.go
  pkg/webhook/preflight/skip/skip.go
  pkg/webhook/preflight/skip/skip_test.go
Labels: feature

#1168 feat: update addons
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/tigera-operator-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: feature

#1179 feat: update Nutanix CSI to 3.3.4
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: feature

#1181 fix: Do not run preflight checks if Cluster is paused
  pkg/webhook/preflight/preflight.go
  pkg/webhook/preflight/preflight_test.go
Labels: fix

#1163 feat: Allow configuration of kube-proxy mode on cluster creation
  api/v1alpha1/clusterconfig_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_genericclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/customization/generic/kube-proxy-mode.md
  pkg/handlers/generic/mutation/extraapiservercertsans/inject_test.go
  pkg/handlers/generic/mutation/handlers.go
  pkg/handlers/generic/mutation/kubeproxymode/embedded/kubeproxyconfig.yaml
  pkg/handlers/generic/mutation/kubeproxymode/inject.go
  pkg/handlers/generic/mutation/kubeproxymode/inject_test.go
  pkg/handlers/generic/mutation/kubeproxymode/variables_test.go
Labels: feature

#1180 fix(preflight): improved error reporting for storage container and VM image checks
  pkg/webhook/preflight/nutanix/image_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
Labels: fix
