Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2025-01, with the labels that each got.

#1008 feat: COSI controller Addon
  api/v1alpha1/addon_types.go
  api/v1alpha1/constants.go
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  api/variables/aggregate_types.go
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/addons/cosi/controller/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cosi/controller/manifests/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.schema.json
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  docs/content/addons/cosi.md
  examples/capi-quick-start/docker-cluster-calico-crs.yaml
  examples/capi-quick-start/docker-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/docker-cluster-cilium-crs.yaml
  examples/capi-quick-start/docker-cluster-cilium-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-calico-crs.yaml
  examples/capi-quick-start/nutanix-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-crs.yaml
  examples/capi-quick-start/nutanix-cluster-cilium-helm-addon.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  hack/addons/kustomize/cosi-controller/kustomization.yaml.tmpl
  hack/examples/bases/docker/cluster/kustomization.yaml.tmpl
  hack/examples/bases/nutanix/cluster/kustomization.yaml.tmpl
  hack/examples/patches/docker/cosi.yaml
  hack/examples/patches/nutanix/cosi.yaml
  hack/tools/fetch-images/main.go
  make/addons.mk
  pkg/handlers/generic/lifecycle/config/cm.go
  pkg/handlers/generic/lifecycle/cosi/doc.go
  pkg/handlers/generic/lifecycle/cosi/handler.go
  pkg/handlers/generic/lifecycle/cosi/variables_test.go
  pkg/handlers/generic/lifecycle/handlers.go
Labels: feature

#1012 fix: update COSI controller image to fix CVEs
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: fix

#1016 fix(deps): Update Nutanix CCM Version
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: fix

#999 release(main): v0.25.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#1018 fix: correctly copy Helm charts in init container
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-repository.yaml
Labels: fix

#1011 feat: adds new field for helm values input for cilium CNI
  api/v1alpha1/addon_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/addons/cni.md
Labels: feature

#1024 fix: Use mindthegap v1.17.0 for the helm-repository container
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
Labels: fix

#1029 fix: update CoreDNS mapping file
  api/versions/coredns.go
  api/versions/coredns_test.go
Labels: fix

#1028 release(release/v0.23.x): v0.23.2
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending
