Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2025-03, with the labels that each got.

#1063 fix: correctly handle multiple registries with the same Host
  pkg/handlers/generic/mutation/mirrors/containerd_files.go
  pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
Labels: fix

#1064 fix: correctly handle multiple registries with the same Host [Backport v0.27.x]
  pkg/handlers/generic/mutation/mirrors/containerd_files.go
  pkg/handlers/generic/mutation/mirrors/containerd_files_test.go
Labels: fix

#1065 release(release/v0.27.x): v0.27.4
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#1066 feat: go 1.24.1 and update all other tools
  .golangci.yml
  api/go.mod
  common/go.mod
  devbox.json
  devbox.lock
  go.mod
  go.sum
  hack/flakes/flake.lock
  hack/flakes/flake.nix
  pkg/handlers/generic/lifecycle/servicelbgc/deleter_test.go
  pkg/handlers/generic/mutation/controlplanevirtualip/providers/kubevip_test.go
Labels: feature

#1067 feat: bumped frr-routing to 9.1.3
  charts/cluster-api-runtime-extensions-nutanix/addons/serviceloadbalancer/metallb/values-template.yaml
Labels: feature

#1072 feat: update addons
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.30.8-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.31.5-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/ccm/aws/manifests/aws-ccm-v1.32.1-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: feature

#1074 fix: Tolerate all NoSchedule taints for NFD and CSI deployments
  charts/cluster-api-runtime-extensions-nutanix/addons/csi/aws-ebs/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/csi/local-path/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/csi/nutanix/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/addons/nfd/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/csi/local-path/manifests/local-path-provisioner-csi-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/nfd/manifests/node-feature-discovery-configmap.yaml
Labels: fix

#1086 feat: enable Cilium's hubble relay mTLS
  charts/cluster-api-runtime-extensions-nutanix/addons/cni/cilium/values-template.yaml
Labels: feature

#1091 fix(deps): update devbox.lock
  devbox.lock
Labels: fix
