Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2025-07, with the labels that each got.

#1186 feat: adds a generic checker package with registry and mirror checks
  cmd/main.go
  go.mod
  go.sum
  pkg/webhook/preflight/generic/checker.go
  pkg/webhook/preflight/generic/registry.go
  pkg/webhook/preflight/generic/registry_test.go
  pkg/webhook/preflight/generic/spec.go
  pkg/webhook/preflight/generic/spec_test.go
Labels: feature

#1194 fix: Include correct field name in registry preflight check results
  pkg/webhook/preflight/generic/registry.go
  pkg/webhook/preflight/generic/registry_test.go
Labels: fix

#1189 feat: deploy registry syncer for workload clusters
  .pre-commit-config.yaml
  api/v1alpha1/constants.go
  api/variables/getters.go
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/addons/registry-syncer/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/registry-syncer/helm-addon-installation.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.schema.json
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
  docs/content/addons/registry.md
  hack/addons/helm-chart-bundler/repos.yaml
  hack/addons/kustomize/registry-syncer/kustomization.yaml.tmpl
  pkg/feature/feature.go
  pkg/handlers/generic/lifecycle/config/cm.go
  pkg/handlers/generic/lifecycle/registry/cncfdistribution/handler.go
  pkg/handlers/generic/lifecycle/registry/handler.go
  pkg/handlers/generic/lifecycle/registry/syncer/syncer.go
  pkg/handlers/generic/lifecycle/registry/syncer/syncer_integration_test.go
  pkg/handlers/generic/lifecycle/registry/syncer/syncer_suite_test.go
  pkg/handlers/generic/lifecycle/registry/syncer/syncer_test.go
  pkg/handlers/generic/lifecycle/registry/syncer/testdata/registry-syncer-template.yaml.tmpl
  pkg/handlers/generic/lifecycle/registry/syncer/testdata/registry-syncer-values.yaml
  pkg/handlers/generic/lifecycle/registry/utils/registry_metadata.go
  pkg/handlers/generic/lifecycle/registry/utils/registry_metadata_test.go
  pkg/webhook/addons/registry/autoenabler.go
Labels: feature

#1172 feat(preflight): Add VM Image kubernetes version check
  pkg/webhook/preflight/nutanix/checker.go
  pkg/webhook/preflight/nutanix/checker_test.go
  pkg/webhook/preflight/nutanix/image.go
  pkg/webhook/preflight/nutanix/image_test.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
Labels: feature

#1192 feat: CAREN support for NutanixFailureDomain
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/conditions.go
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/nutanixcluster_types.go
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/nutanixfailuredomain_types.go
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/nutanixmachine_types.go
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/zz_generated.deepcopy.go
  api/v1alpha1/controlplane_types.go
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixworkernodeconfigs.yaml
  api/v1alpha1/nodeconfig_types.go
  api/v1alpha1/nutanix_node_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/variables/aggregate_types.go
  hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
  hack/third-party/capx/go.mod
  hack/third-party/capx/go.sum
  pkg/handlers/generic/mutation/kubeproxymode/variables_test.go
  pkg/handlers/nutanix/mutation/controlplanefailuredomains/inject.go
  pkg/handlers/nutanix/mutation/controlplanefailuredomains/inject_test.go
  pkg/handlers/nutanix/mutation/controlplanefailuredomains/variables_test.go
  pkg/handlers/nutanix/mutation/machinedetails/variables_test.go
  pkg/handlers/nutanix/mutation/metapatch_handler.go
  pkg/webhook/preflight/nutanix/checker_test.go
  pkg/webhook/preflight/nutanix/image_test.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
  test/e2e/data/shared/v1beta1-capx/metadata.yaml
Labels: feature

#1195 fix: Do not treat expected preflight check failures as internal errors
  pkg/webhook/preflight/generic/registry.go
  pkg/webhook/preflight/generic/registry_test.go
  pkg/webhook/preflight/generic/spec.go
  pkg/webhook/preflight/generic/spec_test.go
  pkg/webhook/preflight/nutanix/credentials.go
  pkg/webhook/preflight/nutanix/credentials_test.go
  pkg/webhook/preflight/nutanix/image.go
  pkg/webhook/preflight/nutanix/image_test.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
  pkg/webhook/preflight/nutanix/specs.go
  pkg/webhook/preflight/nutanix/specs_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
  pkg/webhook/preflight/preflight.go
  pkg/webhook/preflight/preflight_test.go
Labels: fix, do not merge

#1198 fix(preflight): sanitize kubernetes version for image name preflight check
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
Labels: fix

#1204 fix: use a better name for registry check
  pkg/webhook/preflight/generic/registry.go
Labels: fix

#1202 fix: Misc. fixes to preflight check results
  pkg/webhook/preflight/generic/registry.go
  pkg/webhook/preflight/generic/registry_test.go
  pkg/webhook/preflight/nutanix/credentials.go
  pkg/webhook/preflight/nutanix/credentials_test.go
  pkg/webhook/preflight/nutanix/image.go
  pkg/webhook/preflight/nutanix/image_test.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
  pkg/webhook/preflight/nutanix/specs.go
  pkg/webhook/preflight/nutanix/specs_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
Labels: fix

#1205 release(main): v0.31.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#1206 fix: Fix typo in field name; use one-line strings to prevent future typos
  pkg/webhook/preflight/generic/registry_test.go
  pkg/webhook/preflight/generic/spec_test.go
  pkg/webhook/preflight/nutanix/credentials.go
  pkg/webhook/preflight/nutanix/image.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
  pkg/webhook/preflight/nutanix/specs.go
  pkg/webhook/preflight/nutanix/specs_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
Labels: fix

#1211 fix: Nuanced image Kubernetes version check errors
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
Labels: fix

#1210 feat: Add context to preflight check messages
  pkg/webhook/preflight/generic/registry.go
  pkg/webhook/preflight/generic/registry_test.go
  pkg/webhook/preflight/generic/spec.go
  pkg/webhook/preflight/generic/spec_test.go
  pkg/webhook/preflight/nutanix/credentials.go
  pkg/webhook/preflight/nutanix/credentials_test.go
  pkg/webhook/preflight/nutanix/image.go
  pkg/webhook/preflight/nutanix/image_test.go
  pkg/webhook/preflight/nutanix/specs.go
  pkg/webhook/preflight/nutanix/specs_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
  pkg/webhook/preflight/preflight.go
  pkg/webhook/preflight/preflight_test.go
Labels: feature

#1213 feat: Skip FD dependent preflight checks when failureDomain configured
  pkg/webhook/preflight/nutanix/checker.go
  pkg/webhook/preflight/nutanix/specs.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
Labels: feature, do not merge

#1207 feat(failuredomains): add failure domain rollout controller
  charts/cluster-api-runtime-extensions-nutanix/templates/role.yaml
  cmd/main.go
  pkg/controllers/failuredomainrollout/controller.go
  pkg/controllers/failuredomainrollout/controller_test.go
  pkg/controllers/failuredomainrollout/doc.go
  pkg/controllers/failuredomainrollout/flags.go
Labels: feature, do not merge

#1214 fix(helm): add failuredomain rollout controller config to helm chart
  charts/cluster-api-runtime-extensions-nutanix/README.md
  charts/cluster-api-runtime-extensions-nutanix/templates/deployment.yaml
  charts/cluster-api-runtime-extensions-nutanix/values.schema.json
  charts/cluster-api-runtime-extensions-nutanix/values.yaml
Labels: fix

#1220 fix(ccm): Update Nutanix CCM to v0.5.2
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: fix

#1215 fix(preflight): check storage containers on all failure domains
  pkg/webhook/preflight/nutanix/clients_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
Labels: fix

#1221 fix: Use JSONPath in check result fields
  pkg/webhook/preflight/generic/registry.go
  pkg/webhook/preflight/generic/registry_test.go
  pkg/webhook/preflight/generic/spec.go
  pkg/webhook/preflight/generic/spec_test.go
Labels: fix

#1218 fix(auto-cert-renewal): adds 0 as valid value for daysBeforeExpiry
  api/v1alpha1/controlplane_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  common/pkg/testutils/capitest/variables.go
  common/pkg/testutils/openapi/cel.go
  common/pkg/testutils/openapi/validate.go
  pkg/handlers/generic/mutation/autorenewcerts/inject.go
  pkg/handlers/generic/mutation/autorenewcerts/inject_test.go
  pkg/handlers/generic/mutation/autorenewcerts/variables_test.go
Labels: fix

#1225 feat: Add more context to MetalLB config apply conflict errors
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
Labels: feature

#1227 feat: Add scale from zero cluster-autoscaler support
  charts/cluster-api-runtime-extensions-nutanix/addons/cluster-autoscaler/values-template.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cluster-autoscaler/manifests/cluster-autoscaler-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  docs/content/addons/cluster-autoscaler.md
  hack/addons/helm-chart-bundler/repos.yaml
  hack/addons/update-cluster-autoscaler.sh
  make/addons.mk
Labels: feature

#1222 release(main): v0.32.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#1230 fix: Namespacesync copies resources after partial copy failure
  pkg/controllers/namespacesync/controller.go
  pkg/controllers/namespacesync/controller_test.go
  pkg/controllers/namespacesync/copy.go
  pkg/controllers/namespacesync/copy_test.go
Labels: fix

#1229 fix: Namespacesync copies resources after partial copy failure
  pkg/controllers/namespacesync/controller.go
  pkg/controllers/namespacesync/controller_test.go
  pkg/controllers/namespacesync/copy.go
  pkg/controllers/namespacesync/copy_test.go
Labels: fix

#1232 feat: Add more context to MetalLB config apply conflict errors
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
Labels: feature

#1231 feat: Add more context to MetalLB config apply conflict errors
  pkg/handlers/generic/lifecycle/serviceloadbalancer/metallb/handler.go
Labels: feature

#1240 fix: More fixes to preflight result messages and fields
  pkg/webhook/preflight/generic/spec.go
  pkg/webhook/preflight/generic/spec_test.go
  pkg/webhook/preflight/nutanix/credentials.go
  pkg/webhook/preflight/nutanix/failuredomain.go
  pkg/webhook/preflight/nutanix/specs.go
  pkg/webhook/preflight/nutanix/specs_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
Labels: fix

#1234 feat: Support context for all Nutanix client calls
  pkg/webhook/preflight/nutanix/clients.go
  pkg/webhook/preflight/nutanix/clients_test.go
  pkg/webhook/preflight/nutanix/credentials_test.go
  pkg/webhook/preflight/nutanix/failuredomain.go
  pkg/webhook/preflight/nutanix/failuredomain_test.go
  pkg/webhook/preflight/nutanix/image.go
  pkg/webhook/preflight/nutanix/image_test.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck.go
  pkg/webhook/preflight/nutanix/imagekubernetesversioncheck_test.go
  pkg/webhook/preflight/nutanix/storagecontainer.go
  pkg/webhook/preflight/nutanix/storagecontainer_test.go
Labels: feature

#1219 feat: Support AWS PlacementGroups
  api/v1alpha1/aws_node_types.go
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_awsworkernodeconfigs.yaml
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/handlers/aws/mutation/metapatch_handler.go
  pkg/handlers/aws/mutation/placementgroup/inject_control_plane.go
  pkg/handlers/aws/mutation/placementgroup/inject_control_plane_test.go
  pkg/handlers/aws/mutation/placementgroup/inject_suite_test.go
  pkg/handlers/aws/mutation/placementgroup/inject_worker.go
  pkg/handlers/aws/mutation/placementgroup/inject_worker_test.go
  pkg/handlers/aws/mutation/placementgroup/variables_test.go
Labels: feature

#1248 fix(deps): Update CAPX to v1.7.0
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/nutanixcluster_types.go
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  hack/examples/bases/nutanix/clusterclass/kustomization.yaml.tmpl
  hack/third-party/capx/go.mod
  hack/third-party/capx/go.sum
Labels: fix
