Repository nutanix-cloud-native/cluster-api-runtime-extensions-nutanix, pull requests merged in 2025-04, with the labels that each got.

#1096 feat: adds image tempalting for capx
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/nutanix_types.go
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/nutanixmachine_types.go
  api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1/zz_generated.deepcopy.go
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixworkernodeconfigs.yaml
  api/v1alpha1/nutanix_node_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/customization/nutanix/machine-details.md
  hack/third-party/capx/go.mod
  hack/third-party/capx/go.sum
  pkg/handlers/nutanix/mutation/machinedetails/inject.go
  pkg/handlers/nutanix/mutation/machinedetails/inject_control_plane_test.go
  pkg/handlers/nutanix/mutation/machinedetails/variables_test.go
  test/e2e/data/shared/v1beta1-capx/metadata.yaml
Labels: feature

#1097 feat: support setting kubeadm ignorePreflightErrors
  api/v1alpha1/crds/caren.nutanix.com_awsclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_awsworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_dockerworkernodeconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixclusterconfigs.yaml
  api/v1alpha1/crds/caren.nutanix.com_nutanixworkernodeconfigs.yaml
  api/v1alpha1/nodeconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/content/customization/generic/node-registration.md
  examples/capi-quick-start/docker-cluster-calico-crs.yaml
  examples/capi-quick-start/docker-cluster-calico-helm-addon.yaml
  examples/capi-quick-start/docker-cluster-cilium-crs.yaml
  examples/capi-quick-start/docker-cluster-cilium-helm-addon.yaml
  hack/examples/patches/initialize-variables.yaml
  pkg/handlers/generic/mutation/handlers.go
  pkg/handlers/generic/mutation/noderegistration/inject_controlplane.go
  pkg/handlers/generic/mutation/noderegistration/inject_controlplane_test.go
  pkg/handlers/generic/mutation/noderegistration/inject_suite_test.go
  pkg/handlers/generic/mutation/noderegistration/inject_worker.go
  pkg/handlers/generic/mutation/noderegistration/inject_worker_test.go
  pkg/handlers/generic/mutation/noderegistration/variables_test.go
Labels: feature

#1100 feat: go 1.24.2 to fix CVE
  api/go.mod
  common/go.mod
  go.mod
Labels: feature

#1101 feat: update Calico to v3.29.3
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/calico/manifests/tigera-operator-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  make/addons.mk
Labels: feature

#1071 release(main): v0.28.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
  metadata.yaml
  test/e2e/config/caren.yaml
  test/e2e/data/shared/v1beta1-caren/metadata.yaml
Labels: autorelease: pending

#1104 fix: use a new version for control-plane and worker mutation handlers
  README.md
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/aws-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/docker-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  docs/content/getting-started/integrating-with-your-clusterclass/_index.md
  hack/examples/overlays/clusterclasses/aws/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/docker/kustomization.yaml.tmpl
  hack/examples/overlays/clusterclasses/nutanix/kustomization.yaml.tmpl
  pkg/handlers/aws/handlers.go
  pkg/handlers/aws/mutation/metapatch_handler.go
  pkg/handlers/docker/handlers.go
  pkg/handlers/docker/mutation/metapatch_handler.go
  pkg/handlers/generic/handlers.go
  pkg/handlers/generic/mutation/metapatch_handler.go
  pkg/handlers/nutanix/handlers.go
  pkg/handlers/nutanix/mutation/metapatch_handler.go
  pkg/handlers/v2/aws/mutation/metapatch_handler.go
  pkg/handlers/v2/docker/mutation/metapatch_handler.go
  pkg/handlers/v2/generic/mutation/handlers.go
  pkg/handlers/v2/generic/mutation/metapatch_handler.go
  pkg/handlers/v2/nutanix/mutation/metapatch_handler.go
Labels: fix

#1105 release(main): v0.28.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#1106 build(deps): Update CAPX to v1.6.1
  hack/third-party/capx/go.mod
  hack/third-party/capx/go.sum
Labels: fix

#1107 fix: update addon versions
  charts/cluster-api-runtime-extensions-nutanix/defaultclusterclasses/nutanix-cluster-class.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/cilium-configmap.yaml
  charts/cluster-api-runtime-extensions-nutanix/templates/helm-config.yaml
  hack/addons/helm-chart-bundler/repos.yaml
  hack/examples/files/kube-vip.yaml
  make/addons.mk
Labels: fix

#1112 release(main): v0.28.2
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending
